### ISSUE TITLE
Wyoming-whisper errors and no timeout on STT error

### ISSUE THREAD

**Issue by luzik** [AlexxIT/StreamAssist#4]
When using Wyoming-whisper docker image I've got this in logs, and STT sensor is 'processing' quite long (I believe it never ends)

```
wyoming-whisper           | ERROR:asyncio:Task exception was never retrieved
wyoming-whisper           | future: <Task finished name='Task-11' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.9/dist-packages/wyoming/server.py:26> exception=ValueError("can't extend empty axis 0 using modes other than 'constant' or 'empty'")>
wyoming-whisper           | Traceback (most recent call last):
wyoming-whisper           |   File "/usr/local/lib/python3.9/dist-packages/wyoming/server.py", line 32, in run
wyoming-whisper           |     if not (await self.handle_event(event)):
wyoming-whisper           |   File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/handler.py", line 61, in handle_event
wyoming-whisper           |     segments, _info = self.model.transcribe(
wyoming-whisper           |   File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/faster_whisper/transcribe.py", line 124, in transcribe
wyoming-whisper           |     features = self.feature_extractor(audio)
wyoming-whisper           |   File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/faster_whisper/feature_extractor.py", line 152, in __call__
wyoming-whisper           |     frames = self.fram_wave(waveform)
wyoming-whisper           |   File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/faster_whisper/feature_extractor.py", line 98, in fram_wave
wyoming-whisper           |     frame = np.pad(frame, pad_width=padd_width, mode="reflect")
wyoming-whisper           |   File "<__array_function__ internals>", line 200, in pad
wyoming-whisper           |   File "/usr/local/lib/python3.9/dist-packages/numpy/lib/arraypad.py", line 815, in pad
wyoming-whisper           |     raise ValueError(
wyoming-whisper           | ValueError: can't extend empty axis 0 using modes other than 'constant' or 'empty'
```

**Comment by AlexxIT** [comment]
There's a pretty clear error here. `I/O error` - ffmpeg (av) can't read data from camera. It can be network problem or camera rtsp problem.

**Comment by AlexxIT** [comment]
I don't think this can be fixed from integration. Just stream problem.
