### ISSUE TITLE
Error: "Config flow could not be loaded"

### ISSUE THREAD

**Issue by that1guy** [AlexxIT/StreamAssist#6]
When I try to config the integration entity I get error: `Config flow could not be loaded`:

<img width="1211" alt="image" src="https://github.com/AlexxIT/StreamAssist/assets/1218940/8e8bcf02-b3e4-473a-a3b2-04c5e006310d">

Logs show error: `AttributeError: type object 'VoiceCommandSegmenter' has no attribute 'vad_mode'`:
```
Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:403
First occurred: 10:06:19 PM (7 occurrences)
Last logged: 10:26:31 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 213, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 265, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 394, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/stream_assist/config_flow.py", line 58, in async_step_init
    defaults.setdefault("vad_mode", VAD.vad_mode)
                                    ^^^^^^^^^^^^
AttributeError: type object 'VoiceCommandSegmenter' has no attribute 'vad_mode'
```

I've tried selecting the entity from list:

<img width="393" alt="image" src="https://github.com/AlexxIT/StreamAssist/assets/1218940/3af9792a-6a43-465c-b2cd-d5374a1a54bf">

I've tried pasting in the go2rtc camera name.

<img width="422" alt="image" src="https://github.com/AlexxIT/StreamAssist/assets/1218940/ab150a58-fe02-453c-9c1d-aedb281cd53b">

Go2RTC

<img width="379" alt="image" src="https://github.com/AlexxIT/StreamAssist/assets/1218940/1add1e2e-a979-490f-a3e8-223b93dc2429">

Here are my default HA Voice Pipeline settings:

<img width="383" alt="image" src="https://github.com/AlexxIT/StreamAssist/assets/1218940/62903a87-4b2f-4fe2-892d-db4aa90d0e51">

Thanks for help @AlexxIT !

**Comment by domneedham** [comment]
Also receiving the same. 

Tried selecting a camera from the Frigate integration and one from the Tapo integration.

**Comment by tbrasser** [comment]
Experiencing the same issue, since none of my camera's (tablets) can do 2 way audio (if anyone knows an android app that can do this please let me know!), I can't test this component as there is no way to set an output media_player.

**Comment by SilentScreamer1991** [comment]
I am also having this problem. Using the AlexxIT SonoffLAN integration with the Sonoff GK-200MP2B camera. The camera is integrated in the AlexxIT WebRTC integration using RTSP. Also directly in the configuration.yaml 'integrated' in Home Assistant using the RTSP-url. Using Home Assistant Cloud instead of Piper and Whisper in the Voice integration of Home Assistant. Using 2023.10.3 Core. There should be a microphone in the camera, although I never used it. I don't know if it's needed to implement this in the Generic Webcam integration, but I haven't managed to do so.

**Comment by that1guy** [comment]
:Nudge: Any updates here by chance?

**Comment by Juliafin** [comment]
Same issue as well!

**Comment by tbrasser** [comment]
Someone's fork is usable! https://github.com/asmsaifs/StreamAssist

Seems to not properly reset after turning off/on though, but we can go from here.

**Comment by AlexxIT** [comment]
Fix in testing in the latest main/master version

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/StreamAssist/releases/tag/v2.0.0
